enabled: true
production-mode: true
grid-size: grid-lg
header-fixed: true
header-animated: true
header-dark: false
header-transparent: false
sticky-footer: true
blog-page: /blog
spectre:
  exp: false
  icons: false
custom_logo:
  user/themes/quark/images/logo/dmd-logo.svg:
    name: dmd-logo.svg
    type: image/svg+xml
    size: 14696
    path: user/themes/quark/images/logo/dmd-logo.svg
custom_logo_mobile: {  }
